export const GETLOGEEDUSERDATAREQ = "GETLOGEEDUSERDATAREQ";
export const GETLOGEEDUSERDATASUCESS = "GETLOGEEDUSERDATASUCESS";
export const GETLOGEEDUSERDATAFAILURE = "GETLOGEEDUSERDATAFAILURE";


export const JOINPRIVATETABLEREQ = "JOINPRIVATETABLEREQ";
export const JOINPRIVATETABLESUCESS = "JOINPRIVATETABLESUCESS";
export const JOINPRIVATETABLEFAILURE = "JOINPRIVATETABLEFAILURE";


export const CREATTOURNAMNETREQ = "CREATTOURNAMNETREQ";
export const CREATTOURNAMNETSUCESS = "CREATTOURNAMNETSUCESS";
export const CREATTOURNAMNETFAILURE = "CREATTOURNAMNETFAILURE";


export const ADMINUSERDATAREQ = "ADMINUSERDATAREQ";
export const ADMINUSERDATASUCESS = "ADMINUSERDATASUCESS";
export const ADMINUSERDATAFAILURE = "ADMINUSERDATAFAILURE";

export const ADMINCREDITREQ = "ADMINUSERCREDITREQ";
export const ADMINCREDITSUCESS = "ADMINUSERCREDITSUCESS";
export const ADMINCREDITFAILURE = "ADMINUSERCREDITFAILURE";

export const ADMINDEBITREQ = "ADMINUSERDEBITREQ";
export const ADMINDEBITSUCESS = "ADMINUSERDEBITSUCESS";
export const ADMINDEBITFAILURE = "ADMINUSERDEBITFAILURE";

export const PLAYPRIVATETABLEREQ = "PLAYPRIVATETABLEREQ";
export const PLAYPRIVATETABLESUCESS = "PLAYPRIVATETABLESUCESS";
export const PLAYPRIVATETABLEFAILURE = "PLAYPRIVATETABLEFAILURE";