'use client'
import { store } from "@/redux/store";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
const inter = Inter({ subsets: ["latin"] });
//  console.log("store",store)

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <head>
        <meta charSet="utf-8" />
        <title>
          Sikka Play: Unleash Thrilling Entertainment with Card Games
        </title>
        <meta content="Discover Sikka Play: Your ultimate destination for exhilarating card games and endless amusement. Immerse in Indian classics like Teen Patti and Marriage, where strategy meets excitement. Join a global community, challenge friends, and showcase your skills on our user-friendly platform with stunning graphics and smooth gameplay." />
        <meta
          content="Sikka Play: Unleash Thrilling Entertainment with Card Games"
          property="og:title"
        />
        <meta
          content="Discover Sikka Play: Your ultimate destination for exhilarating card games and endless amusement. Immerse in Indian classics like Teen Patti and Marriage, where strategy meets excitement. Join a global community, challenge friends, and showcase your skills on our user-friendly platform with stunning graphics and smooth gameplay."
          property="og:description"
        />
        <meta
          content="Sikka Play: Unleash Thrilling Entertainment with Card Games"
          property="twitter:title"
        />
        <meta
          content="https://furation-tech-solutions-assets.s3.ap-south-1.amazonaws.com/favicon.png"
          property="og:image"
        />
        <meta
          content="https://furation-tech-solutions-assets.s3.ap-south-1.amazonaws.com/favicon.png"
          property="twitter:image"
        />
        <link
          href="/assets/fabicon/favicon.png"
          rel="shortcut icon"
          type="image/x-icon"
        />
        <link href="/assets/fabicon/favicon.png" rel="apple-touch-icon" />
        <link rel="icon" href="/assets/fabicon/favicon.png" sizes="32x32" />
        <link rel="icon" href="/assets/fabicon/favicon.png" sizes="192x192" />
        <link rel="apple-touch-icon" href="/assets/fabicon/favicon.png" />
        <meta
          name="msapplication-TileImage"
          content="/assets/fabicon/favicon.png"
        />
        <meta
          content="Discover Sikka Play: Your ultimate destination for exhilarating card games and endless amusement. Immerse in Indian classics like Teen Patti and Marriage, where strategy meets excitement. Join a global community, challenge friends, and showcase your skills on our user-friendly platform with stunning graphics and smooth gameplay."
          property="twitter:description"
        />
        <meta property="og:type" content="website" />
        <meta content="summary_large_image" name="twitter:card" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
      </head>
      <body className="font-roboto">
        <Provider store={store} >{children}</Provider>
      </body>
    </html>
  );
}
