export const LOGINUSERREQ = "LOGINUSERREQ";
export const LOGINUSERSUCESS = "LOGINUSERSUCESS";
export const LOGINUSERFAILURE = "LOGINUSERFAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const SIGNUPUSERREQ = "SIGNUPUSERREQ";
export const SIGNUPUSERSUCESS = "SIGNUPUSERSUCESS";
export const SIGNUPUSERFAILURE = "SIGNUPUSERFAILURE";

export const USERUPDATEDAVATARREQ = "USERUPDATEDAVATARREQ";
export const USERUPDATEDAVATARSUCESS = "USERUPDATEDAVATARSUCESS";
export const USERUPDATEDAVATARFAILURE = "USERUPDATEDAVATARFAILURE";

export const USEREDIT_DATA_REQUEST = "USEREDIT_DATA_REQUEST";
export const USEREDIT_DATA_SUCESS = "USEREDIT_DATA_SUCESS";
export const USEREDIT_DATA_FAILURE = "USEREDIT_DATA_FAILURE";

export const USEREDIT_IMAGE_REQUEST = "USEREDIT_IMAGE_REQUEST";
export const USEREDIT_IMAGE_SUCESS = "USEREDIT_IMAGE_SUCESS";
export const USEREDIT_IMAGE_FAILURE = "USEREDIT_IMAGE_FAILURE";


export const DELETEUSERREQ = "DELETEUSERREQ";
export const DELETEUSERSUCESS = "DELETEUSERSUCESS";
export const DELETENUSERFAILURE = "DELETEUSERFAILURE";


export const ADMINUSERREQ = "ADMINUSERREQ";
export const ADMINUSERSUCESS = "ADMINUSERSUCESS";
export const ADMINUSERFAILURE = "ADMINUSERFAILURE";


export const PHONELOGINUSERREQ = "PHONELOGINUSERREQ";
export const PHONELOGINUSERSUCESS = "PHONELOGINUSERSUCESS";
export const PHONELOGINUSERFAILURE = "PHONELOGINUSERFAILURE";
